from __future__ import annotations

import datetime as dt
import hashlib
import json
import math
from pathlib import Path

import run_pr62_p_final_recertification as final
from openpyxl import load_workbook

_ROOT = Path(__file__).resolve().parents[1]
_EVIDENCE = _ROOT / final.OUTPUT_JSON
_EXPECTED = {
    "6": {
        "selected": "ad0ebdf717ff9c9e5aa79bbfe2ae36082875b5bb57620d917f9dec695374174b",
        "anchor": "ad0ebdf717ff9c9e5aa79bbfe2ae36082875b5bb57620d917f9dec695374174b",
        "pareto": 47,
        "access_safe": 41,
        "materiality": 5,
        "trips": (78, 78),
        "fleet": (20, 20),
        "classification": "ONE_TRIP_MATERIALITY_SELECTS_ANCHOR",
        "te": 20.923773759043776,
    },
    "10": {
        "selected": "e76426dc2e4420d7f826c939f40d5fb1ea3414744bba3a1a379eb19bc9d4cb24",
        "anchor": "bb35aa0cc7221a887be8328d18de289447ef4070fa147820546efad691fb719c",
        "pareto": 11,
        "access_safe": 7,
        "materiality": 2,
        "trips": (51, 51),
        "fleet": (12, 13),
        "classification": "ONE_TRIP_MATERIALITY_SELECTS_SIMPLER_ALTERNATIVE",
        "te": 17.669451511448948,
    },
}
_SHEETS = {
    "6": [
        "Summary",
        "Timetable",
        "ServiceRegimes",
        "Demand_Comparison",
        "Comparison",
        "Fleet_Plan",
        "Layover_Robustness",
    ],
    "10": [
        "Summary",
        "Timetable",
        "ServiceRegimes",
        "Demand_Comparison",
        "Comparison",
        "Fleet_Plan",
    ],
}


def _payload() -> dict:
    assert _EVIDENCE.is_file(), "P evidence must be generated by the recertification workflow"
    return json.loads(_EVIDENCE.read_text(encoding="utf-8"))


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _seconds(value: dt.time | float) -> int:
    if isinstance(value, dt.time):
        return value.hour * 3600 + value.minute * 60 + value.second
    return round(float(value) * 86400)


def test_o_evidence_lock_and_frozen_production_authority() -> None:
    payload = _payload()
    assert payload["O_commit_SHA"] == "91702bae7d9b2a93afa6f470b3838f8b51e5a6df"
    assert payload["O_evidence_lock"] == {
        "json": {
            "bytes": 133912,
            "sha256": "91a93fa7e7abd4ede3e6848b241b0a3aa22f8f4942aa202c93dad6631df46346",
        },
        "markdown": {
            "bytes": 3215,
            "sha256": "c1a5937f861284f40d5fb050357790d2d2a79b45531ad092baea211f5d804c7c",
        },
    }
    assert payload["policy"]["profile"] == "one_trip_te_materiality_operational_selector_v2"
    assert payload["policy"]["te_materiality_band_trips"] == 1.0
    assert payload["search_budget"] == {
        "max_service_plan_evaluations": 24,
        "max_open_states": 512,
        "max_compile_frontier_per_state": 4,
        "max_directional_compilations": 24,
        "max_pair_frontier": 512,
    }


def test_live_v2_selection_reproduces_route_locks() -> None:
    for route_id, expected in _EXPECTED.items():
        route = _payload()["routes"][route_id]
        assert route["selected_pair_fingerprint"] == expected["selected"]
        assert route["common_anchor_fingerprint"] == expected["anchor"]
        assert route["pareto_count"] == expected["pareto"]
        assert route["hard_feasible_count"] == expected["pareto"]
        assert route["access_safe_count"] == expected["access_safe"]
        assert len(route["materiality_set_fingerprints"]) == expected["materiality"]
        assert route["selection_classification"] == expected["classification"]
        assert route["pareto_fingerprint_reproduced"] is True


def test_exact_departures_endpoints_regimes_protection_and_tails() -> None:
    for route_id, expected in _EXPECTED.items():
        route = _payload()["routes"][route_id]
        for direction, trip_total in zip(("outbound", "inbound"), expected["trips"], strict=True):
            item = route["directions"][direction]
            departures = item["exact_departures"]
            assert len(departures) == trip_total
            assert departures[0] == item["authoritative_first_departure"]
            assert departures[-1] == item["authoritative_last_departure"]
            assert all(value % 60 == 0 for value in departures)
            assert all(a < b for a, b in zip(departures, departures[1:], strict=False))
            assert [
                value for regime in item["service_regimes"] for value in regime["departures"]
            ] == departures
            for regime in item["service_regimes"]:
                gaps = [
                    (b - a) // 60
                    for a, b in zip(regime["departures"], regime["departures"][1:], strict=False)
                ]
                assert not gaps or set(gaps) == {regime["uniform_headway_minutes"]}
            assert item["protection_passed"] is True
            assert item["tail_ordering"]["eligible"] is True
            assert item["compilation_fingerprint"]
        assert route["settlement_used"] is False
        assert route["selected_timetable_manually_edited"] is False


def test_fleet_is_fresh_feasible_and_covers_every_trip_once() -> None:
    for route_id, expected in _EXPECTED.items():
        route = _payload()["routes"][route_id]
        required, ceiling = expected["fleet"]
        plan = route["fleet_plan"]
        assert plan["fleet_required"] == required
        assert route["fleet_ceiling"] == ceiling
        assert plan["fleet_required"] <= route["fleet_ceiling"]
        assert plan["all_connections_pass"] is True
        assert plan["minimum_connection_layover"] >= route["official_minimum_layover_minutes"]
        actual = [item["trip_id"] for item in plan["assignments"]]
        wanted = {
            *(
                f"OUTBOUND-{index:03d}"
                for index in range(1, len(route["directions"]["outbound"]["exact_departures"]) + 1)
            ),
            *(
                f"INBOUND-{index:03d}"
                for index in range(1, len(route["directions"]["inbound"]["exact_departures"]) + 1)
            ),
        }
        assert len(actual) == len(wanted)
        assert set(actual) == wanted


def test_directional_access_and_te_recompute_exactly() -> None:
    for route_id, expected in _EXPECTED.items():
        route = _payload()["routes"][route_id]
        for direction in ("outbound", "inbound"):
            access = route["access"][direction]
            assert (
                access["selected_maximum_bucket_wait_minutes"]
                <= access["scenario_b_maximum_bucket_wait_minutes"] + final.NUMERICAL_EPSILON
            )
            metrics = route["directions"][direction]["metrics"]
            counts, demand, service = (
                metrics["bucket_service_counts"],
                metrics["bucket_demand_shares"],
                metrics["bucket_service_shares"],
            )
            trips = len(route["directions"][direction]["exact_departures"])
            assert len(counts) == len(demand) == len(service) > 0
            assert sum(counts) == trips
            assert math.isclose(sum(demand), 1.0, abs_tol=final.NUMERICAL_EPSILON)
            assert math.isclose(sum(service), 1.0, abs_tol=final.NUMERICAL_EPSILON)
            assert all(
                math.isclose(share, count / trips, abs_tol=final.NUMERICAL_EPSILON)
                for count, share in zip(counts, service, strict=True)
            )
        assert math.isclose(route["te"]["pair"], expected["te"], abs_tol=1e-12)
        assert math.isclose(
            route["te"]["pair"], route["te"]["outbound"] + route["te"]["inbound"], abs_tol=1e-12
        )


def test_route10_extreme_tails_are_excluded_before_materiality() -> None:
    exclusion = _payload()["routes"]["10"]["access_exclusions"]
    assert exclusion["classification"] == "ACCESS_EXCLUDED_BEFORE_MATERIALITY"
    assert {30, 45, 48, 54}.issubset(
        {item["inbound_tail_headway"] for item in exclusion["candidates"]}
    )


def test_route6_ten_minute_sensitivity_is_recomputed_without_trip_shifts() -> None:
    sensitivity = _payload()["routes"]["6"]["layover_robustness"]["sensitivity"]
    assert sensitivity["minimum_layover_minutes"] == 10
    assert sensitivity["departure_shifts"] == 0
    assert sensitivity["all_connections_pass"] is True
    expected = (
        "STATIC_TIMETABLE_ROBUST_AT_10"
        if sensitivity["fleet_required"] <= 20
        else "STATIC_TIMETABLE_NOT_ROBUST_AT_10"
    )
    assert sensitivity["classification"] == expected


def test_historical_g_archives_match_committed_g_authority() -> None:
    payload = _payload()
    expected = {
        "6": "35a4ef65b0bc64cc8e18397c27bc7a135d5039857321f06e5ec5aadf15bf8879",
        "10": "e49031892388714850001c0a97f91db9e3380b2dc0808d45095ce9825abf9da0",
    }
    for route_id, sha256 in expected.items():
        archive = _ROOT / payload["historical_g_archive"][route_id]["path"]
        assert _sha256(archive) == sha256
        assert payload["historical_g_archive"][route_id]["g_hash_match"] is True
    assert (
        _sha256(_ROOT / "docs/engine/evidence/PR62_G_FINAL_PILOT_SELECTION.json")
        == "cb651c16761dc62d071ae1192228f852c0651b841c1ace07172811388f8f256f"
    )
    assert (
        _sha256(_ROOT / "docs/engine/evidence/PR62_G_FINAL_PILOT_SELECTION.md")
        == "32660893cb93ef3a5c38724a02f7eeffde0293a6a8a5aae9b6e03a8639b6ceb0"
    )


def test_logical_fingerprint_accepts_historical_g_route_schema() -> None:
    evidence = json.loads(
        (_ROOT / "docs/engine/evidence/PR62_G_FINAL_PILOT_SELECTION.json").read_text(
            encoding="utf-8"
        )
    )
    route = evidence["routes"]["6"]
    path = _ROOT / "outputs/final_pilot/archive/pr62_g" / Path(route["workbook"]["path"]).name
    assert (
        final.logical_workbook_fingerprint(path, route) == route["workbook"]["logical_fingerprint"]
    )


def test_workbooks_match_selected_vectors_fleet_universe_and_sheet_order() -> None:
    for route_id, expected in _EXPECTED.items():
        route = _payload()["routes"][route_id]
        workbook = load_workbook(
            _ROOT / route["workbook"]["path"], data_only=False, keep_links=True
        )
        assert workbook.sheetnames == _SHEETS[route_id]
        assert not workbook._external_links
        summary = workbook["Summary"]
        summary_values = {
            summary.cell(row=row, column=1).value: summary.cell(row=row, column=2).value
            for row in range(3, summary.max_row + 1)
        }
        assert summary_values["Selected pair fingerprint"] == expected["selected"]
        assert summary_values["Certification status"] == "PILOT_FINAL_RECERTIFIED_V2"
        timetable = workbook["Timetable"]
        for direction, column in (("outbound", 2), ("inbound", 7)):
            departures = route["directions"][direction]["exact_departures"]
            assert [
                _seconds(timetable.cell(row=index + 2, column=column).value)
                for index in range(len(departures))
            ] == departures
        fleet = workbook["Fleet_Plan"]
        assert [fleet.cell(row=row, column=2).value for row in range(2, fleet.max_row + 1)] == [
            item["trip_id"] for item in route["fleet_plan"]["assignments"]
        ]


def test_workbook_generation_and_evidence_are_deterministic() -> None:
    payload = _payload()
    assert payload["deterministic_evidence_render"] is True
    for route_id in ("6", "10"):
        workbook = payload["routes"][route_id]["workbook"]
        assert (
            workbook["logical_fingerprint_generation_1"]
            == workbook["logical_fingerprint_generation_2"]
        )
        path = _ROOT / workbook["path"]
        assert (
            final.logical_workbook_fingerprint(path, payload["routes"][route_id])
            == workbook["logical_fingerprint"]
        )
        assert workbook["formula_error_count"] == 0
        assert workbook["visual_verification_passed"] is True


def test_final_certification_and_readiness_require_both_routes() -> None:
    payload = _payload()
    assert all(
        payload["routes"][route_id]["certification_classification"]
        == "FINAL_V2_TIMETABLE_RECERTIFIED"
        for route_id in ("6", "10")
    )
    assert payload["cross_route_classification"] == "FINAL_PILOT_PRODUCTS_RECERTIFIED_V2"
    assert payload["READY_FOR_FINAL_PILOT_USE"] is True
    assert payload["READY_FOR_PR62_COMPLETION_REVIEW"] is True


def test_evidence_records_completed_validation_gates() -> None:
    validation = _payload()["validation_result"]
    assert validation["status"] == "PASSED"
    assert validation["focused_p_and_g_tests"] == "PASSED"
    assert validation["requested_regression_suites"] == "PASSED"
    assert validation["artifact_tool_staged_and_canonical_verification"] == "PASSED"
    assert validation["deterministic_workbook_generation"] == "PASSED"
    assert validation["ruff"] == "PASSED"
    assert validation["format_check"] == "PASSED"
    assert validation["python_compilation"] == "PASSED"
    assert validation["mjs_syntax_and_runtime"] == "PASSED"
    assert validation["git_diff_check"] == "PASSED"
