"""Bus Schedule Engine MVP."""

from .importer import ImportedWorkbook, WorkbookAuthorityMetadata
from .input_authority import (
    WorkbookInputReadinessV1,
    WorkbookOptimizationAuthorityError,
    assess_workbook_input_readiness_v1,
    normalization_options_from_workbook_v1,
)
from .models import (
    AnalysisBundle,
    DemandRecord,
    Direction,
    RouteType,
    ScenarioParameters,
    Trip,
)
from .optimization_service import (
    BusScheduleOptimizationResult,
    OptimizationAction,
    SolverChoice,
    SolverComparisonV1,
    analyze_and_optimize_schedule_v1,
    select_optimization_action,
)
from .side_by_side_validation import (
    ComparisonCategoryV1,
    ComparisonDispositionV1,
    ComparisonRuleV1,
    ComparisonStatusV1,
    FactComparisonRecordV1,
    LegacyPathSnapshotV1,
    SideBySideValidationReportV1,
    TimetableSnapshotV1,
    TimetableTripSnapshotV1,
    UnifiedPathSnapshotV1,
    run_side_by_side_validation_v1,
    side_by_side_report_to_dict,
)
from .unified_diagram import (
    build_unified_demand_supply_figure_v1,
    build_unified_departure_figure_v1,
)
from .unified_presentation import (
    PRESENTATION_MODE_VALIDATION_ONLY,
    PresentationBlockV1,
    PresentationDemandGapV1,
    PresentationDimensionV1,
    PresentationDiscrepancyV1,
    PresentationFleetAssignmentV1,
    PresentationHeadwayRegimeV1,
    PresentationInitialFleetV1,
    PresentationOutcomeV1,
    PresentationScenarioV1,
    PresentationTripV1,
    UnifiedPresentationBundleV1,
    UnifiedPresentationConsistencyError,
    build_unified_presentation_v1,
    unified_presentation_to_dict,
)
from .unified_result_exporter import (
    UnifiedExportMetadataV1,
    export_unified_result_workbook_v1,
    read_unified_export_metadata_v1,
)

__all__ = [
    "AnalysisBundle",
    "BusScheduleOptimizationResult",
    "ComparisonCategoryV1",
    "ComparisonDispositionV1",
    "ComparisonRuleV1",
    "ComparisonStatusV1",
    "DemandRecord",
    "Direction",
    "FactComparisonRecordV1",
    "ImportedWorkbook",
    "LegacyPathSnapshotV1",
    "OptimizationAction",
    "PRESENTATION_MODE_VALIDATION_ONLY",
    "PresentationBlockV1",
    "PresentationDemandGapV1",
    "PresentationDimensionV1",
    "PresentationDiscrepancyV1",
    "PresentationFleetAssignmentV1",
    "PresentationHeadwayRegimeV1",
    "PresentationInitialFleetV1",
    "PresentationOutcomeV1",
    "PresentationScenarioV1",
    "PresentationTripV1",
    "RouteType",
    "ScenarioParameters",
    "SideBySideValidationReportV1",
    "SolverComparisonV1",
    "SolverChoice",
    "TimetableSnapshotV1",
    "TimetableTripSnapshotV1",
    "Trip",
    "UnifiedExportMetadataV1",
    "UnifiedPresentationBundleV1",
    "UnifiedPresentationConsistencyError",
    "UnifiedPathSnapshotV1",
    "WorkbookAuthorityMetadata",
    "WorkbookInputReadinessV1",
    "WorkbookOptimizationAuthorityError",
    "analyze_and_optimize_schedule_v1",
    "assess_workbook_input_readiness_v1",
    "build_unified_demand_supply_figure_v1",
    "build_unified_departure_figure_v1",
    "build_unified_presentation_v1",
    "export_unified_result_workbook_v1",
    "normalization_options_from_workbook_v1",
    "run_side_by_side_validation_v1",
    "read_unified_export_metadata_v1",
    "select_optimization_action",
    "side_by_side_report_to_dict",
    "unified_presentation_to_dict",
]
