"""Stable Milestone 6A2A classification and evidence codes."""

PROTECTED_HIGH_DEMAND_SERVICE_FLOOR = "PROTECTED_HIGH_DEMAND_SERVICE_FLOOR"
NOT_EVALUATED_NO_TRIP_RIDERSHIP = "NOT_EVALUATED_NO_TRIP_RIDERSHIP"
NOT_EVALUATED_STALE_TRIP_RIDERSHIP = "NOT_EVALUATED_STALE_TRIP_RIDERSHIP"
NOT_EVALUATED_TRIP_RIDERSHIP_FAILED = "NOT_EVALUATED_TRIP_RIDERSHIP_FAILED"
NOT_EVALUATED_CONFIDENCE_BELOW_MINIMUM = "NOT_EVALUATED_CONFIDENCE_BELOW_MINIMUM"
NOT_PROTECTED_B_REGIME_NOT_REGULAR = "NOT_PROTECTED_B_REGIME_NOT_REGULAR"
NOT_PROTECTED_HEADWAY_NOT_MEASURABLE = "NOT_PROTECTED_HEADWAY_NOT_MEASURABLE"
NOT_PROTECTED_HEADWAY_ABOVE_CEILING = "NOT_PROTECTED_HEADWAY_ABOVE_CEILING"
NOT_PROTECTED_TOO_FEW_DEPARTURES = "NOT_PROTECTED_TOO_FEW_DEPARTURES"
NOT_PROTECTED_REGIME_TOO_SHORT = "NOT_PROTECTED_REGIME_TOO_SHORT"
NOT_PROTECTED_INSUFFICIENT_TRIP_COVERAGE = "NOT_PROTECTED_INSUFFICIENT_TRIP_COVERAGE"
NOT_PROTECTED_HIGH_LOAD_SHARE_BELOW_THRESHOLD = "NOT_PROTECTED_HIGH_LOAD_SHARE_BELOW_THRESHOLD"
NOT_PROTECTED_NO_COVERAGE_ELIGIBLE_TRIPS = "NOT_PROTECTED_NO_COVERAGE_ELIGIBLE_TRIPS"
NOT_PROTECTED_EVIDENCE_NOT_BOUND_TO_CURRENT_B = "NOT_PROTECTED_EVIDENCE_NOT_BOUND_TO_CURRENT_B"

REGULAR = "REGULAR"
BALANCED_ROUNDING = "BALANCED_ROUNDING"
HEADWAY_NOT_MEASURABLE = "HEADWAY_NOT_MEASURABLE"
IRREGULAR_NON_POSITIVE_HEADWAY = "IRREGULAR_NON_POSITIVE_HEADWAY"
IRREGULAR_NON_WHOLE_MINUTE_HEADWAY = "IRREGULAR_NON_WHOLE_MINUTE_HEADWAY"
IRREGULAR_HEADWAY_RANGE_EXCEEDS_TOLERANCE = "IRREGULAR_HEADWAY_RANGE_EXCEEDS_TOLERANCE"

ORDERED_BY_DEPARTURE_TIME_THEN_TRIP_ID = "ORDERED_BY_DEPARTURE_TIME_THEN_TRIP_ID"
DIRECTION_DERIVED_INDEPENDENTLY = "DIRECTION_DERIVED_INDEPENDENTLY"
OPERATING_WINDOW_START = "OPERATING_WINDOW_START"
OPERATING_WINDOW_END = "OPERATING_WINDOW_END"
MATERIAL_SUSTAINED_SERVICE_RATE_CHANGE = "MATERIAL_SUSTAINED_SERVICE_RATE_CHANGE"
TRANSITION_GAP_EXCLUDED_FROM_INTERNAL_HEADWAYS = "TRANSITION_GAP_EXCLUDED_FROM_INTERNAL_HEADWAYS"

MISSING_TRIP_OBSERVATIONS_ARE_NOT_ZERO = "MISSING_TRIP_OBSERVATIONS_ARE_NOT_ZERO"
UNOBSERVED_TRIP_DAYS_ARE_NOT_EXTRAPOLATED = "UNOBSERVED_TRIP_DAYS_ARE_NOT_EXTRAPOLATED"
INSUFFICIENT_OBSERVED_DAYS_EXCLUDED_FROM_COVERAGE = (
    "INSUFFICIENT_OBSERVED_DAYS_EXCLUDED_FROM_COVERAGE"
)
P85_LOAD_FACTOR_UNAVAILABLE = "P85_LOAD_FACTOR_UNAVAILABLE"
UNSAFE_MATCH_RECORDS_EXCLUDED = "UNSAFE_MATCH_RECORDS_EXCLUDED"
SUPPLEMENTAL_PLANNING_EVIDENCE_ONLY = "SUPPLEMENTAL_PLANNING_EVIDENCE_ONLY"
NOT_ENFORCED_IN_6A2A = "NOT_ENFORCED_IN_6A2A"

PROTECTED_SERVICE_FLOOR_ASSESSMENT_FAILED = "PROTECTED_SERVICE_FLOOR_ASSESSMENT_FAILED"

FAILED_GATE_ORDER = (
    NOT_EVALUATED_NO_TRIP_RIDERSHIP,
    NOT_EVALUATED_STALE_TRIP_RIDERSHIP,
    NOT_EVALUATED_TRIP_RIDERSHIP_FAILED,
    NOT_EVALUATED_CONFIDENCE_BELOW_MINIMUM,
    NOT_PROTECTED_B_REGIME_NOT_REGULAR,
    NOT_PROTECTED_HEADWAY_NOT_MEASURABLE,
    NOT_PROTECTED_HEADWAY_ABOVE_CEILING,
    NOT_PROTECTED_TOO_FEW_DEPARTURES,
    NOT_PROTECTED_REGIME_TOO_SHORT,
    NOT_PROTECTED_INSUFFICIENT_TRIP_COVERAGE,
    NOT_PROTECTED_NO_COVERAGE_ELIGIBLE_TRIPS,
    NOT_PROTECTED_HIGH_LOAD_SHARE_BELOW_THRESHOLD,
    NOT_PROTECTED_EVIDENCE_NOT_BOUND_TO_CURRENT_B,
)

__all__ = [name for name in globals() if name.isupper()]
