"""Canonical issue codes for supplemental trip-ridership import and analysis."""

TRIP_RIDERSHIP_METADATA_MISSING = "TRIP_RIDERSHIP_METADATA_MISSING"
TRIP_RIDERSHIP_DATASET_ID_MISSING = "TRIP_RIDERSHIP_DATASET_ID_MISSING"
TRIP_RIDERSHIP_SOURCE_TYPE_INVALID = "TRIP_RIDERSHIP_SOURCE_TYPE_INVALID"
TRIP_RIDERSHIP_CONFIDENCE_INVALID = "TRIP_RIDERSHIP_CONFIDENCE_INVALID"
TRIP_RIDERSHIP_SCENARIO_INVALID = "TRIP_RIDERSHIP_SCENARIO_INVALID"
TRIP_RIDERSHIP_OPERATING_DAY_TYPE_MISMATCH = "TRIP_RIDERSHIP_OPERATING_DAY_TYPE_MISMATCH"
TRIP_RIDERSHIP_MATCH_TOLERANCE_INVALID = "TRIP_RIDERSHIP_MATCH_TOLERANCE_INVALID"
DUPLICATE_TRIP_RIDERSHIP_OBSERVATION_ID = "DUPLICATE_TRIP_RIDERSHIP_OBSERVATION_ID"
TRIP_RIDERSHIP_DIRECTION_INVALID = "TRIP_RIDERSHIP_DIRECTION_INVALID"
TRIP_RIDERSHIP_COMBINED_DIRECTION_NOT_ALLOWED = "TRIP_RIDERSHIP_COMBINED_DIRECTION_NOT_ALLOWED"
TRIP_RIDERSHIP_PASSENGER_COUNT_INVALID = "TRIP_RIDERSHIP_PASSENGER_COUNT_INVALID"
TRIP_RIDERSHIP_REFERENCE_MISSING = "TRIP_RIDERSHIP_REFERENCE_MISSING"
TRIP_RIDERSHIP_FORMULA_NOT_ALLOWED = "TRIP_RIDERSHIP_FORMULA_NOT_ALLOWED"
EXPLICIT_SCHEDULED_TRIP_ID_NOT_FOUND = "EXPLICIT_SCHEDULED_TRIP_ID_NOT_FOUND"
EXPLICIT_TRIP_DIRECTION_MISMATCH = "EXPLICIT_TRIP_DIRECTION_MISMATCH"
EXPLICIT_SCHEDULED_TIME_MISMATCH = "EXPLICIT_SCHEDULED_TIME_MISMATCH"
NO_TRIP_WITHIN_MATCH_TOLERANCE = "NO_TRIP_WITHIN_MATCH_TOLERANCE"
AMBIGUOUS_TRIP_TIME_MATCH = "AMBIGUOUS_TRIP_TIME_MATCH"
DUPLICATE_OBSERVATION_FOR_TRIP_DATE = "DUPLICATE_OBSERVATION_FOR_TRIP_DATE"
TRIP_RIDERSHIP_NO_USABLE_MATCHES = "TRIP_RIDERSHIP_NO_USABLE_MATCHES"
TRIP_RIDERSHIP_ANALYSIS_FAILED = "TRIP_RIDERSHIP_ANALYSIS_FAILED"

__all__ = [
    "AMBIGUOUS_TRIP_TIME_MATCH",
    "DUPLICATE_OBSERVATION_FOR_TRIP_DATE",
    "DUPLICATE_TRIP_RIDERSHIP_OBSERVATION_ID",
    "EXPLICIT_SCHEDULED_TIME_MISMATCH",
    "EXPLICIT_SCHEDULED_TRIP_ID_NOT_FOUND",
    "EXPLICIT_TRIP_DIRECTION_MISMATCH",
    "NO_TRIP_WITHIN_MATCH_TOLERANCE",
    "TRIP_RIDERSHIP_ANALYSIS_FAILED",
    "TRIP_RIDERSHIP_COMBINED_DIRECTION_NOT_ALLOWED",
    "TRIP_RIDERSHIP_CONFIDENCE_INVALID",
    "TRIP_RIDERSHIP_DATASET_ID_MISSING",
    "TRIP_RIDERSHIP_DIRECTION_INVALID",
    "TRIP_RIDERSHIP_FORMULA_NOT_ALLOWED",
    "TRIP_RIDERSHIP_MATCH_TOLERANCE_INVALID",
    "TRIP_RIDERSHIP_METADATA_MISSING",
    "TRIP_RIDERSHIP_NO_USABLE_MATCHES",
    "TRIP_RIDERSHIP_OPERATING_DAY_TYPE_MISMATCH",
    "TRIP_RIDERSHIP_PASSENGER_COUNT_INVALID",
    "TRIP_RIDERSHIP_REFERENCE_MISSING",
    "TRIP_RIDERSHIP_SCENARIO_INVALID",
    "TRIP_RIDERSHIP_SOURCE_TYPE_INVALID",
]
